#!/usr/bin/env python3
"""Regenerate INDEX.md from entry frontmatter. Deterministic and idempotent.

Run after any change under entries/. Do not hand-edit INDEX.md.
"""
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from validate_entries import ENTRIES_DIR, parse_frontmatter  # noqa: E402


def main():
    by_topic = defaultdict(list)

    for path in sorted(ENTRIES_DIR.rglob("*.md")) if ENTRIES_DIR.exists() else []:
        text = path.read_text(encoding="utf-8")
        fm, _ = parse_frontmatter(text)
        if not fm:
            continue
        topic = path.parent.name
        rel = path.as_posix()
        by_topic[topic].append((fm.get("title", path.stem), rel, fm.get("summary", "")))

    lines = [
        "# Knowledge Bank Index",
        "",
        "Auto-generated by scripts/build_index.py. Do not edit by hand.",
        "Read this file first. Open individual entries only when a topic is relevant.",
        "",
    ]

    for topic in sorted(by_topic):
        lines.append(f"## {topic}")
        lines.append("")
        for title, rel, summary in sorted(by_topic[topic]):
            lines.append(f"- [{title}]({rel}) — {summary}")
        lines.append("")

    Path("INDEX.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    total = sum(len(v) for v in by_topic.values())
    print(f"Wrote INDEX.md with {total} entries across {len(by_topic)} topics.")


if __name__ == "__main__":
    main()
